version: '3'
services:
  backend:
    build:
      context:./server  
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend  
    ports:
      - "5000:5000"
    depends_on:
      - backend
